# 빌드 설정을 정의합니다.
[build]
  functions = "./functions"

# 리다이렉트 규칙을 정의합니다. (기존 설정 유지)
# /api/ 로 시작하는 모든 요청을 gemini 함수로 전달합니다.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gemini/:splat"
  status = 200
  force = true
